# Generated by Django 5.0.5 on 2024-05-13 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='superAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superAdminName', models.CharField(max_length=50)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminName', models.CharField(max_length=50)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('superAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productDetails.superadmin')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('userName', models.CharField(max_length=50)),
                ('gmail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productDetails.admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('productName', models.CharField(max_length=50)),
                ('productDescription', models.TextField()),
                ('productCreatedDate', models.DateTimeField(auto_now_add=True)),
                ('productUpdatedDate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productDetails.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
